[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NPM_FLAGS = "--include=dev"
  NPM_CONFIG_PRODUCTION = "false"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
